export const foods = [
    {
        groupId: "MSS",
        groupTitle: "MENU SHAWARMA SPECIAL",
        itemId: 1,
        itemName: "MENU SHAWARMA POULET",
        itemDescription: "Pain Saj maison, Shawarma de Poulet, crème à l'ail, cornichons, frites, boissons",
        itemPrice: 12.00,
        itemMainPhoto: "assets/images/photo1.jpg",
    },
    {
        groupId: "MSS",
        groupTitle: "MENU SHAWARMA SPECIAL",
        itemId: 2,
        itemName: "SHAWARMA POULET",
        itemDescription: "Pain Saj maison, Shawarma de Poulet, crème à l'ail, cornichons",
        itemPrice: 8.00,
        itemMainPhoto: "assets/images/photo1.jpg",
    },
    {
        groupId: "MSS",
        groupTitle: "MENU SHAWARMA SPECIAL",
        itemId: 3,
        itemName: "BOX SHAWARMA POULET ARABIC",
        itemDescription: "Sandwich shawarma poulet découpé en bouchées accompagner de frites et de salade de chou traditionnelle",
        itemPrice: 10.00,
        itemMainPhoto: "assets/images/BOX_SHAWARMA_POULET_ARABIC.jpg",
    },
    {
        groupId: "SV",
        groupTitle: "SPECIALITE VEGETARIENNE",
        itemId: 4,
        itemName: "MENU SANDWICH FALAFEL",
        itemDescription: "Boulette croquante composée de pois chiche, épices douces, salade, tomate, crème de sésame, frites, boisson",
        itemPrice: 11.00,
        itemMainPhoto: "assets/images/MENU_SANDWICH_FALAFEL.jpg",
    },
    {
        groupId: "SV",
        groupTitle: "SPECIALITE VEGETARIENNE",
        itemId: 5,
        itemName: "SANDWICH FALAFEL",
        itemDescription: "Boulette croquante composée de pois chiche, épices douces, salade, tomate, crème de sésame",
        itemPrice: 7.00,
        itemMainPhoto: "assets/images/SANDWICH_FALAFEL.jpg",
    },
    {
        groupId: "SV",
        groupTitle: "SPECIALITE VEGETARIENNE",
        itemId: 6,
        itemName: "BOX FALAFEL",
        itemDescription: "5 falafels, salade composée, houmous, servis avec du pain libanais",
        itemPrice: 10.00,
        itemMainPhoto: "assets/images/BOX_FALAFEL.jpg",
    },
    {
        groupId: "EF",
        groupTitle: "ENTREE FROIDE",
        itemId: 6,
        itemName: "HOUMOUS",
        itemDescription: "Purée de pois chiche rehaussé de crèmme de sésames, jus de citron et un filet d'huile d'olive",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/HOUMOUS.jpg",
    },
    {
        groupId: "EF",
        groupTitle: "ENTREE FROIDE",
        itemId: 7,
        itemName: "MOUTABAL",
        itemDescription: "Aubergines grillés, crème de sésames, jus de citron et un filet d'huile d'olive",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/MOUTABAL.jpg",
    },
    {
        groupId: "EF",
        groupTitle: "ENTREE FROIDE",
        itemId: 8,
        itemName: "WARAK ENAB (x6)",
        itemDescription: "Feuille de vigne farcie de riz, tomate fraîche, persils",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/WARAK_ENAB.jpg",
    },
    {
        groupId: "EF",
        groupTitle: "ENTREE FROIDE",
        itemId: 9,
        itemName: "FATTOUCHE",
        itemDescription: "Salade composée assaisonnée de sauce faite maison à base d'épices, huile d'olive, jus de citron et du pain grillé",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/FATTOUCHE.jpg",
    },
    {
        groupId: "EC",
        groupTitle: "ENTREE CHAUDE",
        itemId: 10,
        itemName: "FATAYER VIANDE (x3)",
        itemDescription: "Baignet de viande hachée de boeuf",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/FATAYER_VIANDE.jpg",
    },
    {
        groupId: "EC",
        groupTitle: "ENTREE CHAUDE",
        itemId: 11,
        itemName: "FATAYER FROMAGE (x3)",
        itemDescription: "Fatayer au fromage",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/Fatayer_au_fromage.jpg",
    },
    {
        groupId: "EC",
        groupTitle: "ENTREE CHAUDE",
        itemId: 12,
        itemName: "SAMBUSSIK (x3)",
        itemDescription: "Baignet d'épinard citronnée avec oignon et sésames",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/SAMBUSSIK.jpg",
    },
    {
        groupId: "EC",
        groupTitle: "ENTREE CHAUDE",
        itemId: 13,
        itemName: "FALAFEL (x6)",
        itemDescription: "",
        itemPrice: 5.00,
        itemMainPhoto: "assets/images/FALAFEL.jpg",
    },
    {
        groupId: "EC",
        groupTitle: "ENTREE CHAUDE",
        itemId: 14,
        itemName: "KEBBE (x3)",
        itemDescription: "Boulette de blé farcie de viande hachée et d'oignon",
        itemPrice: 6.00,
        itemMainPhoto: "assets/images/KEBBE.jpg",
    },
    {
        groupId: "MEN",
        groupTitle: "MENU ENFANT",
        itemId: 15,
        itemName: "MENU TENDERS",
        itemDescription: "avec frites et caprisun",
        itemPrice: 7.50,
        itemMainPhoto: "assets/images/MENU_TENDERS.jpg",
    },
    {
        groupId: "MEN",
        groupTitle: "MENU ENFANT",
        itemId: 16,
        itemName: "MENU ROULE SHAWARMA",
        itemDescription: "sauce au choix, frites, caprisun",
        itemPrice: 7.50,
        itemMainPhoto: "assets/images/MENU_SHAWARMA_POULET.jpg",
    },
    {
        groupId: "MET",
        groupTitle: "MENU ETUDIANT",
        itemId: 17,
        itemName: "MENU SHAWARMA POULET",
        itemDescription: "Shawarma poulet, frites, boisson",
        itemPrice: 8.50,
        itemMainPhoto: "assets/images/MENU_SHAWARMA_POULET.jpg",
    },
    {
        groupId: "MET",
        groupTitle: "MENU ETUDIANT",
        itemId: 18,
        itemName: "MENU SANDWICH FALAFEL",
        itemDescription: "Sandwich falafel, frites, boisson",
        itemPrice: 8.50,
        itemMainPhoto: "assets/images/MENU_SANDWICH_FALAFEL.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 19,
        itemName: "Coca cola",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Coca_cola.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 20,
        itemName: "Coca cherry",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Coca_cherry.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 21,
        itemName: "Coca zéro",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Coca_zero.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 22,
        itemName: "Ice tea",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Ice_tea.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 23,
        itemName: "Seven up",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Seven_up.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 24,
        itemName: "Oasis",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Oasis.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 25,
        itemName: "Ayran",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Ayran.jpg",
    },
    {
        groupId: "BOISS",
        groupTitle: "BOISSONS",
        itemId: 26,
        itemName: "Eau minérale",
        itemDescription: "",
        itemPrice: 2.00,
        itemMainPhoto: "assets/images/Eau_minerale.jpg",
    },
    {
        groupId: "DESS",
        groupTitle: "DESSERT",
        itemId: 27,
        itemName: "MOUHALABIEH",
        itemDescription: "Flan syrien au lait parfumé de fleur d'oranger, pistache",
        itemPrice: 4.00,
        itemMainPhoto: "assets/images/MOUHALABIEH.jpg",
    },
    {
        groupId: "DESS",
        groupTitle: "DESSERT",
        itemId: 28,
        itemName: "KATAYEF (x2)",
        itemDescription: "Mini crêpe syrienne fourrée de crème de noix avec un coulis de sirop au sucre",
        itemPrice: 4.00,
        itemMainPhoto: "assets/images/KATAYEF.jpg",
    },
    {
        groupId: "DESS",
        groupTitle: "DESSERT",
        itemId: 29,
        itemName: "TIRAMISU",
        itemDescription: "",
        itemPrice: 4.00,
        itemMainPhoto: "assets/images/TIRAMISU.jpg",
    },
    {
        groupId: "DESS",
        groupTitle: "DESSERT",
        itemId: 30,
        itemName: "TARTE AU DAIM",
        itemDescription: "",
        itemPrice: 4.00,
        itemMainPhoto: "assets/images/TARTEAUDAIM.jpg",
    },
    {
        groupId: "SUP",
        groupTitle: "SUPPLEMENT",
        itemId: 31,
        itemName: "ACCOMPAGNEMENT SUPPLEMENTAIRE",
        itemDescription: "brquette de frite 3.50€ et boisson au choix 2€",
        itemPrice: 0
    }
]